# Generated by Django 4.2.5 on 2023-09-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bruger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=255)),
                ('brugernavn', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longtitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribed_kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bruger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svendeORMAndAPI.bruger')),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svendeORMAndAPI.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Billeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('beskrivelse', models.TextField()),
                ('billedet', models.ImageField(upload_to='media/images')),
                ('geo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svendeORMAndAPI.geo')),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svendeORMAndAPI.kategori')),
                ('upload_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svendeORMAndAPI.bruger')),
            ],
        ),
    ]
