# Generated by Django 4.2.5 on 2023-10-05 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("svendeORMAndAPI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rapport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beskrivelse", models.TextField()),
                (
                    "billed_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="svendeORMAndAPI.billeder",
                    ),
                ),
                (
                    "snitch_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="svendeORMAndAPI.bruger",
                    ),
                ),
            ],
        ),
    ]
